export { default as Header } from './Header';
export { default as Footer } from './Footer';
export { default as MovieCard } from './MovieCard';
export { default as FIlterSelection } from './Filters/FIlterSelection';
export { default as FilterButton } from './Filters/FilterButton';
export { default as Logo } from './Logo';
export { default as CustomSwiperSlide } from './Swiper/CustomSwiperSlide';
export { default as CustomSwiperNavigation } from './Swiper/CustomSwiperNavigation';
export { default as PostersGallery } from './PostersGallery';
